os: linux
dist: xenial
language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - dev

install:
  - yarn install
  - yarn lint:all
  - yarn static:ci

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: dev
